#!/usr/bin/env bash
# Reproducible deployment on a fresh EC2 box (CPU is fine).
#
#   git clone <this repo> wagon_eye_global_integrated
#   cd wagon_eye_global_integrated
#   WITH_OCR=0 bash scripts/setup_ec2.sh
#
# Creates the virtualenv, installs the wheels, clones (or fast-forwards) the
# EXTERNAL counting engine, writes wagoneye.env, and finishes with preflight.
#
# Nothing is hardcoded: every path is an environment variable with a default
# relative to $HOME or the repo, so the same script works on any machine.
#
#   ENGINE_DIR        where the counting engine is cloned  (~/global_count_ec2)
#   RECON_MODELS_DIR  the five counting weights            (~/global_wagon_models)
#   FEAT_MODELS_DIR   the feature weights                  (<repo>/models/features)
#   VENV_DIR          the virtualenv                       (<repo>/.venv)
#   PYTHON_BIN        interpreter used to build the venv   (python3)
#   WITH_OCR          0 skips the heavy easyocr install    (1)
#
# Example -- engine and weights somewhere else entirely:
#   ENGINE_DIR=/opt/global_count_ec2 RECON_MODELS_DIR=/opt/weights \
#       bash scripts/setup_ec2.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENGINE_REPO_URL="${ENGINE_REPO_URL:-https://github.com/AjayKhatik-s2/global_count_ec2.git}"
ENGINE_DIR="${ENGINE_DIR:-$HOME/global_count_ec2}"
RECON_MODELS_DIR="${RECON_MODELS_DIR:-$HOME/global_wagon_models}"
FEAT_MODELS_DIR="${FEAT_MODELS_DIR:-$REPO_ROOT/models/features}"
VENV_DIR="${VENV_DIR:-$REPO_ROOT/.venv}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
WITH_OCR="${WITH_OCR:-1}"

say() { printf '\n=== %s ===\n' "$1"; }

say "1/5  virtualenv  ->  $VENV_DIR"
if [ ! -d "$VENV_DIR" ]; then
    "$PYTHON_BIN" -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
. "$VENV_DIR/bin/activate"
python -m pip install --upgrade pip setuptools wheel

say "2/5  python dependencies"
if [ "$WITH_OCR" = "1" ]; then
    pip install -r "$REPO_ROOT/requirements.txt"
else
    # OCR is the only heavy optional dependency. Skip it when the pipeline will
    # run with --features door,load,damage.
    TMP_REQ="$(mktemp)"
    grep -v -i '^easyocr' "$REPO_ROOT/requirements.txt" > "$TMP_REQ"
    pip install -r "$TMP_REQ"
    rm -f "$TMP_REQ"
    echo "easyocr SKIPPED (WITH_OCR=0) -- do not pass 'ocr' to --features"
fi

say "3/5  external counting engine  ->  $ENGINE_DIR"
# The validated engine lives in its OWN repository and is deliberately not
# vendored here, so the counting algorithm has exactly one source of truth.
# This pipeline drives it; it never copies or modifies it.
if [ -d "$ENGINE_DIR/.git" ]; then
    git -C "$ENGINE_DIR" pull --ff-only
else
    git clone "$ENGINE_REPO_URL" "$ENGINE_DIR"
fi

if [ -f "$ENGINE_DIR/global_wagon_pipeline.py" ]; then
    RESOLVED_ENGINE="$ENGINE_DIR"
elif [ -f "$ENGINE_DIR/global_wagon_app/global_wagon_pipeline.py" ]; then
    RESOLVED_ENGINE="$ENGINE_DIR/global_wagon_app"
else
    echo "ERROR: no global_wagon_pipeline.py under $ENGINE_DIR" >&2
    exit 1
fi
echo "engine package: $RESOLVED_ENGINE"

# The engine has its own requirements (pandas, tqdm, matplotlib ...).
if [ -f "$RESOLVED_ENGINE/requirements.txt" ]; then
    say "3b/5  engine dependencies"
    pip install -r "$RESOLVED_ENGINE/requirements.txt"
elif [ -f "$ENGINE_DIR/requirements.txt" ]; then
    say "3b/5  engine dependencies"
    pip install -r "$ENGINE_DIR/requirements.txt"
fi

say "4/5  environment file  ->  $REPO_ROOT/wagoneye.env"
cat > "$REPO_ROOT/wagoneye.env" <<ENVEOF
# Generated by scripts/setup_ec2.sh -- source this before running the pipeline.
export GLOBAL_WAGON_APP_DIR="$RESOLVED_ENGINE"
export WAGONEYE_RECON_MODELS_DIR="$RECON_MODELS_DIR"
export WAGONEYE_FEAT_MODELS_DIR="$FEAT_MODELS_DIR"
# Set to wagon_count to roll Stage 1 back to the retained subprocess counter.
# export WAGONEYE_STAGE1_ENGINE=wagon_count
ENVEOF
echo "source wagoneye.env   # then run the orchestrator"

say "5/5  preflight"
# shellcheck disable=SC1091
. "$REPO_ROOT/wagoneye.env"
FEATURES="all"
[ "$WITH_OCR" = "1" ] || FEATURES="door,load,damage"
python "$REPO_ROOT/scripts/preflight.py" \
    --recon-models-dir "$RECON_MODELS_DIR" \
    --feat-models-dir "$FEAT_MODELS_DIR" \
    --features "$FEATURES" || true

cat <<DONEEOF

Setup finished. Weights are NOT downloaded by this script -- put them in place:

  $RECON_MODELS_DIR
      side_classification.pt  top_classification.pt
      right_up_wagon_gap.pt   left_up_wagon_gap.pt   top_gap.pt
      (right_up_gap.pt / left_up_gap.pt are accepted too)

  $FEAT_MODELS_DIR
      door_state.pt  loaded.pt  damage.pt  wagon_id_counting.pt

Then re-run scripts/preflight.py until it says READY TO RUN.
DONEEOF
